import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { adaptAgentInstructions } from "./codex-agent-instructions";
import { PREFIX_BY_PLUGIN } from "./codex-agent-prefixes";
import { effortForAlias, mapToCodexModel } from "./codex-model-mapper";
import type { CodexRuntimePaths } from "./codex-runtime";

export interface ConvertedAgent {
	fileName: string;
	name: string;
	toml: string;
}

const MCP_BY_AGENT: Record<string, readonly string[]> = {
	"research-expert": ["context7", "exa"],
	"design-expert": ["gemini-design", "magic"],
	websearch: ["exa"],
};

const safeName = (v: string) => v.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
const tomlStr = (v: string) => JSON.stringify(v);
const tomlBlock = (v: string) =>
	`"""\n${v.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"').trim()}\n"""`;
const pluginSlug = (p: string) => (PREFIX_BY_PLUGIN[p] || safeName(p)).replace(/_/g, "-");

function parseAgentMarkdown(text: string): { body: string; meta: Record<string, string> } {
	const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
	if (!m) return { body: text.trim(), meta: {} };
	const meta: Record<string, string> = {};
	for (const line of m[1].split(/\r?\n/)) {
		const i = line.indexOf(":");
		if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim().replace(/^["']|["']$/g, "");
	}
	return { body: m[2].trim(), meta };
}

function sandboxFor(d: string, b: string): string | undefined {
	return /read-only|no file modifications|do not make code changes/.test(`${d}\n${b}`.toLowerCase()) ? "read-only" : undefined;
}

function mcpBlock(name: string): string {
	const s = MCP_BY_AGENT[name];
	return s ? s.map((id) => `\n[mcp_servers.${id}]`).join("") + "\n" : "";
}

function agentToml(plugin: string, sourcePath: string, pluginsDir: string, text: string): ConvertedAgent {
	const { body, meta } = parseAgentMarkdown(text);
	if (!body.trim()) throw new Error(`Empty body — developer_instructions would be empty: ${sourcePath}`);
	const originalName = meta.name || basename(sourcePath, ".md");
	const slug = pluginSlug(plugin);
	const name = `${slug.replace(/-/g, "_")}_${safeName(originalName)}`;
	const description = meta.description || `${originalName} agent from ${plugin}`;
	const codexModel = mapToCodexModel(meta.model);
	const relSource = relative(pluginsDir, sourcePath) || basename(sourcePath);
	const instructions = adaptAgentInstructions(
		[`Source plugin: ${plugin}`, `Source agent: ${relSource}`, "", body].join("\n"),
	);
	const lines = [
		"# Generated by Fusengine setup from plugin agent Markdown.",
		`name = ${tomlStr(name)}`,
		`description = ${tomlStr(description)}`,
		`model_reasoning_effort = ${tomlStr(effortForAlias(meta.model))}`,
	];
	if (codexModel) lines.push(`model = ${tomlStr(codexModel)}`);
	const sandbox = sandboxFor(description, body);
	if (sandbox) lines.push(`sandbox_mode = ${tomlStr(sandbox)}`);
	lines.push(`developer_instructions = ${tomlBlock(instructions)}`, mcpBlock(originalName));
	return { fileName: `${slug}-${safeName(originalName).replace(/_/g, "-")}.toml`, name, toml: lines.join("\n") };
}

/** Convert plugin Markdown agents to Codex TOML descriptors. */
export function convertPluginAgents(pluginsDir: string): ConvertedAgent[] {
	if (!existsSync(pluginsDir)) return [];
	return readdirSync(pluginsDir, { withFileTypes: true })
		.filter((e) => e.isDirectory())
		.flatMap((e) => {
			const agentsDir = join(pluginsDir, e.name, "agents");
			if (!existsSync(agentsDir)) return [];
			return readdirSync(agentsDir)
				.filter((f) => f.endsWith(".md"))
				.map((f) => agentToml(e.name, join(agentsDir, f), pluginsDir, readFileSync(join(agentsDir, f), "utf8")));
		});
}

/** Install converted agents; cleans both legacy `fusengine-*` and new `<slug>-*` files. */
export function installCodexAgents(paths: CodexRuntimePaths): void {
	const agents = convertPluginAgents(join(paths.marketplaceRoot, "plugins"));
	mkdirSync(paths.agentsDir, { recursive: true });
	const slugs = Object.values(PREFIX_BY_PLUGIN).map((p) => p.replace(/_/g, "-"));
	for (const file of readdirSync(paths.agentsDir)) {
		if (!file.endsWith(".toml")) continue;
		if (file.startsWith("fusengine-") || slugs.some((s) => file.startsWith(`${s}-`))) {
			rmSync(join(paths.agentsDir, file), { force: true });
		}
	}
	for (const agent of agents) writeFileSync(join(paths.agentsDir, agent.fileName), agent.toml);
}
