import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { adaptAgentInstructions } from "./codex-agent-instructions";
import { PREFIX_BY_PLUGIN } from "./codex-agent-prefixes";
import type { CodexRuntimePaths } from "./codex-runtime";

export interface ConvertedAgent {
	fileName: string;
	name: string;
	toml: string;
}

function safeName(value: string): string {
	return value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function parseFrontmatter(text: string): { body: string; meta: Record<string, string> } {
	const match = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
	if (!match) return { body: text.trim(), meta: {} };
	const meta: Record<string, string> = {};
	for (const line of match[1].split(/\r?\n/)) {
		const index = line.indexOf(":");
		if (index <= 0) continue;
		const key = line.slice(0, index).trim();
		const value = line.slice(index + 1).trim().replace(/^["']|["']$/g, "");
		meta[key] = value;
	}
	return { body: match[2].trim(), meta };
}

function tomlString(value: string): string {
	return JSON.stringify(value);
}

function tomlBlock(value: string): string {
	const escaped = value.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');
	return `"""\n${escaped.trim()}\n"""`;
}

function effortFor(model: string): "high" | "medium" {
	return model.toLowerCase() === "opus" ? "high" : "medium";
}

function sandboxFor(description: string, body: string): string | undefined {
	const text = `${description}\n${body}`.toLowerCase();
	return /read-only|no file modifications|do not make code changes/.test(text)
		? "read-only"
		: undefined;
}

function agentToml(plugin: string, sourcePath: string, text: string): ConvertedAgent {
	const { body, meta } = parseFrontmatter(text);
	const originalName = meta.name || basename(sourcePath, ".md");
	const name = `${PREFIX_BY_PLUGIN[plugin] || safeName(plugin)}_${safeName(originalName)}`;
	const description = meta.description || `${originalName} agent from ${plugin}`;
	const sandbox = sandboxFor(description, body);
	const instructions = adaptAgentInstructions(
		[`Source plugin: ${plugin}`, `Source agent: ${sourcePath}`, "", body].join("\n"),
	);
	const lines = [
		"# Generated by Fusengine setup from plugin agent Markdown.",
		`name = ${tomlString(name)}`,
		`description = ${tomlString(description)}`,
		`model_reasoning_effort = ${tomlString(effortFor(meta.model || ""))}`,
	];
	if (sandbox) lines.push(`sandbox_mode = ${tomlString(sandbox)}`);
	lines.push(`developer_instructions = ${tomlBlock(instructions)}`, "");
	return { fileName: `fusengine-${name.replace(/_/g, "-")}.toml`, name, toml: lines.join("\n") };
}

export function convertPluginAgents(pluginsDir: string): ConvertedAgent[] {
	if (!existsSync(pluginsDir)) return [];
	return readdirSync(pluginsDir, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.flatMap((entry) => {
			const agentsDir = join(pluginsDir, entry.name, "agents");
			if (!existsSync(agentsDir)) return [];
			return readdirSync(agentsDir)
				.filter((file) => file.endsWith(".md"))
				.map((file) => {
					const path = join(agentsDir, file);
					return agentToml(entry.name, path, readFileSync(path, "utf8"));
				});
		});
}

export function installCodexAgents(paths: CodexRuntimePaths): void {
	const agents = convertPluginAgents(join(paths.marketplaceRoot, "plugins"));
	mkdirSync(paths.agentsDir, { recursive: true });
	for (const file of readdirSync(paths.agentsDir).filter((name) => name.startsWith("fusengine-"))) {
		rmSync(join(paths.agentsDir, file), { force: true });
	}
	for (const agent of agents) writeFileSync(join(paths.agentsDir, agent.fileName), agent.toml);
}
