#!/usr/bin/env python3
"""Generate multi-level navigable ecosystem map with links.

Level 1: index.md — compact plugin list with links
Level 2: {plugin}/index.md — plugin detail with links to skills/agents
Level 3+: recursive branches down to leaves (real source files)
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.detect_plugins import find_marketplace_plugins, read_plugin_meta
from lib.merge_index import merge_lines
from lib.scan_plugins import scan_plugin
from lib.write_plugin_map import write_plugin_map


def main() -> None:
    """Orchestrate multi-level map generation."""
    arg1 = sys.argv[1] if len(sys.argv) > 1 else ""
    arg2 = sys.argv[2] if len(sys.argv) > 2 else ""  # noqa: PLR2004

    plugins_dir = (
        find_marketplace_plugins() if arg1 == "auto"
        else Path(arg1) if arg1
        else Path(__file__).resolve().parent.parent.parent
    )
    output_dir = (
        plugins_dir.parent / ".cartographer" if arg2 == "auto"
        else Path(arg2) if arg2
        else Path(".cartographer")
    )

    plugins_dir = plugins_dir.resolve()
    if not plugins_dir.is_dir():
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    plugin_dirs = sorted(
        d for d in plugins_dir.iterdir()
        if d.is_dir() and not d.name.startswith(("_", "."))
    )

    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
    index_lines = [
        f"# Ecosystem Map ({len(plugin_dirs)} plugins)\n",
        f"> Auto-generated by cartographer — {now}\n",
    ]

    for plugin_path in plugin_dirs:
        version, pkg_name = read_plugin_meta(plugin_path)
        display = pkg_name or plugin_path.name
        items = scan_plugin(str(plugin_path))
        agents = [n for t, n, _ in items if t == "agent"]
        agents_str = ", ".join(agents) if agents else "(no agents)"
        ver = f" (v{version})" if version else ""
        index_lines.append(
            f"- [{display}](./{display}/index.md){ver} → {agents_str}",
        )
        write_plugin_map(output_dir, display, version, items, plugin_path)
        write_plugin_map(
            plugin_path, ".cartographer", version, items, plugin_path,
        )

    index_path = output_dir / "index.md"
    merged = merge_lines(index_lines, index_path)
    index_path.write_text(
        "\n".join(merged) + "\n",
        encoding="utf-8",
    )

    count = len(plugin_dirs)
    print(f"cart plugins: {count} loaded", file=sys.stderr)

    context = (
        f"Project map: .cartographer/project/index.md — navigate project files. "
        f"Plugin skills map: {output_dir}/index.md — navigate agent skills. "
        f"Branches link to deeper index.md, leaves link to real files."
    )
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "SessionStart",
        "additionalContext": context,
    }}))
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        pass
